
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Text</h1>
        </header>
        {children}
        <footer>
          <p>Copy Right @2025 shruti</p>
        </footer>
      </body>
    </html>
  )
}
